---
output: github_document
---

# DataVizR

## Installation

```{r, warning=FALSE, message=FALSE}
# install.packages("devtools")
devtools::install_github("deadhand7/data-viz-r")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(DataVizR)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/",
  warning = FALSE,
  message = FALSE
)
```


## Overview

The package provides a palette based on Europace color codes and a custom theme which uses the Europace fronts. Additionally, some flexible quick-access plotting functions are included.

### Main Functions

* ```ep.theme()```
* ```scale.fill.ep()```
* ```scale.color.ep```
* ```plot.histogram```
* ```plot.density```
* ```plot.boxplot```

### Customize an existing ggplot

```{r}
iris %>% 
  ggplot(aes(x = Species, y = Sepal.Width, fill = Species)) +
  geom_violin() +
  scale.fill.ep('cool') +
  ep.theme()
```

### Histogram

```{r}
plot.histogram(df = mtcars, x = mpg, binwidth = 1, ticks = 5)  
```

### Facets

```{r}
DataVizR::plot.histogram(df = iris, x = Petal.Width, binwidth = 1, facet = Species, ticks = 3)  
```

### Density Plot

```{r}
plot.density(df = mtcars, x = qsec)  
```

### Box-Plot

```{r}
plot.boxplot(df = iris, x = Species, y = Sepal.Length, fill = Species, x.lab = 'Species', ticks = 4)
```

